// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbmxelhrflcemjertsip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibXhlbGhyZmxjZW1qZXJ0c2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzY3NTksImV4cCI6MjA2MjIxMjc1OX0.nPTxoY1YTIltUgJj1PhXnz1TUFR9PC3m971_tXxJEYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);